version: '{branch}-{build}'

branches:
  only:
    - master
    - develop

image:
- Visual Studio 2017

configuration:
- Release
- Debug

platform:
- Win32
- x64

before_build:
- md build
- cd build
- cmake -Wno-dev -A%PLATFORM% ..

build_script:
- cmake --build . --config "%CONFIGURATION%"

test_script:
- ctest -C "%CONFIGURATION%" --output-on-failure
