sudo: required
os: linux
dist: trusty
language: cpp

branches:
  only:
    - master
    - develop

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-7']
      env:
        - CXX=g++-7
        - CXXSTD=-std=c++17
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8']
      env:
        - CXX=g++-8
        - CXXSTD=-std=c++17
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0']
          packages: ['clang-6.0', 'g++-7']
      env:
        - CXX=clang++-6.0
        - CXXSTD=-std=c++17
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"

before_install:
  - wget -O cmake.sh https://cmake.org/files/v3.10/cmake-3.10.0-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr
  - export PATH="/usr/bin:${PATH}"
  - cmake --version
  - eval "${MATRIX_EVAL}"

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - mkdir build && cd build
  - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE

script:
  - cmake --build .
  - ctest --output-on-failure
